name: qrl
channels:
  - defaults
dependencies:
  - pip==23.3.1
  - python=3.10.14
  - pip:
    - aiofile==3.8.8
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.2
    - anyio==4.3.0
    - appdirs==1.4.4
    - argcomplete==3.3.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - autograd==1.6.2
    - autoray==0.6.9
    - azure-core==1.30.1
    - azure-identity==1.16.0
    - azure-quantum==0.28.277227
    - azure-storage-blob==12.19.1
    - babel==2.14.0
    - backoff==2.2.1
    - backports-entry-points-selectable==1.3.0
    - basis-set-exchange==0.9.1
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - boltons==24.0.0
    - boto3==1.34.92
    - botocore==1.34.92
    - cachetools==5.3.3
    - caio==0.9.13
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==2.2.1
    - comm==0.2.2
    - contourpy==1.2.1
    - cryptography==42.0.5
    - cycler==0.12.1
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.14
    - dill==0.3.8
    - dimod==0.12.14
    - distlib==0.3.8
    - dm-tree==0.1.8
    - docplex==2.25.236
    - dwave-neal==0.6.0
    - dwave-samplers==1.2.0
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - farama-notifications==0.0.4
    - fastjsonschema==2.19.1
    - filelock==3.13.4
    - fonttools==4.51.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - future==1.0.0
    - grpcio==1.62.2
    - gymnasium==0.26.3
    - gymnasium-notices==0.0.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - idna==3.7
    - imageio==2.34.1
    - importlib-metadata==7.1.0
    - ipykernel==6.29.4
    - ipython==8.24.0
    - ipywidgets==8.0.6
    - isodate==0.6.1
    - isoduration==20.11.0
    - jax-jumpy==1.0.0
    - jedi==0.19.1
    - jinja2==3.1.3
    - jmespath==1.0.1
    - json5==0.9.25
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-contrib-core==0.4.2
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-jsmol==2022.1.0
    - jupyter-lsp==2.2.5
    - jupyter-nbextensions-configurator==0.6.3
    - jupyter-server==2.14.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.7
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.1
    - jupyterlab-widgets==3.0.10
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - lz4==4.3.3
    - markdown==3.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.0.2
    - mpmath==1.3.0
    - msal==1.28.0
    - msal-extensions==1.1.0
    - msgpack==1.0.8
    - msrest==0.7.1
    - multidict==6.0.5
    - mypy-extensions==1.0.0
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.3
    - ninja==1.11.1.1
    - notebook==7.1.3
    - notebook-shim==0.2.4
    - numpy==1.26.4
    - oauthlib==3.2.2
    - openpulse==0.5.0
    - openqaoa==0.2.5
    - openqaoa-azure==0.2.5
    - openqaoa-braket==0.2.5
    - openqaoa-core==0.2.5
    - openqaoa-qiskit==0.2.5
    - openqasm3==0.5.0
    - opt-einsum==3.3.0
    - oqpy==0.3.5
    - overrides==7.7.0
    - packaging==24.0
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pbr==6.0.0
    - pennylane==0.27.0
    - pennylane-lightning==0.28.0
    - pexpect==4.9.0
    - pillow==10.3.0
    - platformdirs==4.2.1
    - ply==3.11
    - portalocker==2.8.2
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - protobuf==3.20.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pyarrow==16.0.0
    - pycparser==2.22
    - pydantic==1.10.15
    - pydantic-core==2.18.2
    - pygments==2.17.2
    - pyjwt==2.8.0
    - pyparsing==3.1.2
    - pyqir==0.8.0
    - pyqubo==1.4.0
    - pyspnego==0.10.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - python-markdown-math==0.8
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==26.0.2
    - qdk==0.29.0
    - qiskit==0.46.1
    - qiskit-aer==0.14.0.1
    - qiskit-algorithms==0.3.0
    - qiskit-ibm-provider==0.11.0
    - qiskit-ionq==0.5.1
    - qiskit-optimization==0.6.1
    - qiskit-qir==0.3.1
    - qiskit-terra==0.46.1
    - qsharp==0.28.302812
    - qsharp-chemistry==0.28.302812
    - qsharp-core==0.28.302812
    - ray==2.3.0
    - referencing==0.35.0
    - regex==2024.4.16
    - requests==2.31.0
    - requests-ntlm==1.2.0
    - requests-oauthlib==2.0.0
    - retry==0.9.2
    - retworkx==0.14.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - rpds-py==0.18.0
    - ruamel-yaml==0.18.6
    - ruamel-yaml-clib==0.2.8
    - rustworkx==0.14.2
    - s3transfer==0.10.1
    - scikit-image==0.23.2
    - scipy==1.13.0
    - semantic-version==2.10.0
    - send2trash==1.8.3
    - setuptools==68.2.2
    - shellingham==1.5.4
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - stevedore==5.2.0
    - symengine==0.11.0
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboardx==2.6.2.2
    - terminado==0.18.1
    - tifffile==2024.4.24
    - tinycss2==1.3.0
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.13.1
    - tornado==6.4
    - traitlets==5.14.3
    - typer==0.12.3
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.11.0
    - tzdata==2024.1
    - unidecode==1.3.8
    - uri-template==1.3.0
    - urllib3==2.2.1
    - varname==0.13.0
    - virtualenv==20.26.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - websockets==12.0
    - wheel==0.41.2
    - widgetsnbextension==4.0.10
    - wrapt==1.16.0
    - yarl==1.9.4
    - zipp==3.18.1
