name: baseline
channels:
- defaults
dependencies:
  - matplotlib
  - numpy=1.21.5
  - pandas=1.4.1
  - pip=21.2.2
  - python=3.11
  - pyyaml=6.0
  - yaml=0.2.5
  - pip:
    - absl-py==1.0.0
    - aiosignal==1.2.0
    - ale-py==0.8.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - autograd==1.5
    - autoray==0.3.2
    - AutoROM==0.4.2
    - AutoROM.accept-rom-license==0.4.2
    - cachetools==5.0.0
    - certifi==2022.9.24
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cloudpickle==2.2.0
    - colorama==0.4.4
    - contourpy==1.0.5
    - cycler==0.11.0
    - Cython==0.29.28
    - decorator==5.1.1
    - Deprecated==1.2.13
    - distlib==0.3.4
    - dm-tree==0.1.6
    - filelock==3.6.0
    - flatbuffers==2.0
    - fonttools==4.37.4
    - frozenlist==1.3.0
    - future==0.18.2
    - gast==0.4.0
    - gekko==1.0.5
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - GPUtil==1.4.0
    - GPy==1.10.0
    - grpcio==1.43.0
    - gymnasium
    - h5py==3.6.0
    - higher==0.2.1
    - idna==3.3
    - imageio==2.16.1
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - joblib==1.1.0
    - jsonschema==4.4.0
    - keras==2.7.0
    - Keras-Preprocessing==1.1.2
    - kiwisolver==1.4.4
    - lazydocs==0.4.8
    - libclang==13.0.0
    - lz4==4.0.2
    - Markdown==3.3.6
    - mdutils==1.3.1
    - msgpack==1.0.3
    - mujoco==2.3.0
    - networkx==2.7.1
    - ninja==1.10.2.4
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - packaging==21.3
    - paramz==0.9.5
    - PennyLane==0.24.0
    - PennyLane-Lightning==0.26.0
    - Pillow==9.2.0
    - platformdirs==2.5.2
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.2
    - pyglet==1.3.2
    - pyparsing==3.0.9
    - pyqubo==1.3.1
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.4
    - PyWavelets==1.4.1
    - qiskit-optimization[cplex]
    - ray==2.6.0
    - redis==4.2.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - retworkx==0.12.0
    - rsa==4.8
    - rustworkx==0.12.0
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - semantic-version==2.6.0
    - six==1.16.0
    - sklearn==0.0
    - sympy==1.11.1
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardX==2.5
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-probability==0.15.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2022.3.25
    - tk==0.1.0
    - toml==0.10.2
    - torch==1.11.0
    - tqdm==4.63.1
    - typer==0.4.0
    - typing_extensions==4.1.1
    - urllib3==1.26.9
    - virtualenv==20.14.1
    - Werkzeug==2.1.0
    - wrapt==1.14.0
    - zipp==3.7.0


