type:                             QRL                   # choose a type: RL, GA, Hypernetwork (DEPRECATED)
alg:                              QPG                   # name of the algorithm
seed:                             42                    # seed for ray alogorithms/tensorflow/pytorch for reproduceabel results
constant_seed:                    False                 # setting the same seed accross all runs
checkpoint_at_end:                False                 # create checkpoint at the end of training
checkpoint_freq:                  100                   # set checkpoint frequency, depends on training iterations
ray_local_mode:                   False                 # set local_mode of ray to True for debugging
ray_logging_path:                 logs/w-maxcut/nodes5/qpg            # logging directory
total_num_cpus:                   10                    # total number of cpus
total_num_gpus:                   0                     # total number of gpus
ray_num_trial_samples:            1                     # number of training seeds per combination
training_iterations:              250                   # number of training iterations
run_sections:                                           # specifiy the code you want to run
                                - qrl_training
                                - plotting

############################## Env Config #############################################
env:                              weightedMaxCut        # specifiy env string                              
env_config:
  nodes:                          5                     # numnber of graph nodes either set to 5 or 10
  mode:                           dynamic               # only dynamic implemented
  reward_mode:                    normal                # either normal or ratio
  annotation_value:               0                     # annotation value (either 0 or 2pi)
  constant:                       False                 # set the training graph constant for testing
  action_space:                   discrete_nodes        # either 'discrete_nodes' or 'discrete_edges' measurements (measurement needs to be set to 'edge' for discrete_edges)       
  reward_at_end:                  False                 # return reward only at end if set True
  callback:                       MaxCut_Callback       # callback to log additional information during training     
  path:                           /home/users/kruse/Hamiltonian-based-QRL # path to dataset needs to be specified (run pwd / current directory)


############################## Alg Config #############################################
algorithm_config:                                       # config for QRL training
  reuse_actors:                   True
  framework:                      torch                 # ray framework [torch, tensorflow]
  ###########################################################################
  lr:                             0.025                 # select lr for nn, variational params and input scaling params
  lr_output_scaling:              0.1                   # select lr for output scaling params
  num_layers:                     5                     # select number of layers of vqc (layer nn defined below)
  ###########################################################################
  mode:                           quantum               # select mode [classical, quantum, hybrid]
  interface:                      torch                 # select pennylane interface, default: torch
  diff_method:                    adjoint               # select pennylane diff_method [adjoing, backprop, ...] 
  backend_name:                   lightning.qubit       # select pennylane backend [lightning.qubit, default.qubit, ...]
  custom_optimizer:               Adam                  # select the classical optimizer [Adam, RMSprop, LBFGS, ...] 
  ###########################################################################
  vqc_type:                       [vqc_generator, 5]    # select vqc_generator or other circuit generator function + number of qubits
  use_hadamard:                   True                  # Create equal superposition in the beginning
  block_sequence:                 enc                   # select the block sequence, enc_var_ent == classical hea ansatz, graph_encoding only needs enc
  encoding_type:                  graph_encoding        # data encoding type [angular_classical (RY_RZ), layerwise_arctan_sigmoid, graph_encoding ... ]
  graph_encoding_type:            sge-sgv               # if encoding_type=graph_encoding, than select [sge-sgv, mge-sgv, mge-mgv, hamiltonian-hea, angular-hea, angular, ...]
  use_input_scaling:              True                  # use input scaling [True, False]
  init_input_scaling_actor:       [1.]                  # if list, then each gate gets one params, if single float, all have same param [[1.], 1., ...]
  num_scaling_params:             2                     # select the number of params, so e.g. 2 for angular_classical -> RY_RZ
  quadratic_gate:                 ZZ                    # ZZ, XX, YY
  linear_gate:                    RZ                    # RZ, RX, RY
  annotations_gate:               RX                    # RZ, RX, RY
  measurement_gate:               PauliZ                # PauliZ, PauliX, PauliY
  variational_type:               RZ_RY                 # select the gate sequence [RZ_RY, RY_RZ]
  num_variational_params:         2                     # select the number of params, so e.g. 2 for RZ_RY
  init_variational_params:        0.1                   # select initialization of the variational parameters
  init_variational_params_mode:   plus-zero-uniform     # plus-zero-uniform, plus-plus-normal, plus-zero-normal
  entangling_type:                chain                 # type of entanglement [chain, full, ...]
  entangling_gate:                CZ                    # type of entanglement gate [CNOT, CZ, CH, ...]
  measurement_type_actor:         exp                  # type of measurement (check the python files for examples) (exp for discrete) exp_@_exp+exp
  use_output_scaling_actor:       True                  # use output scaling [True, False]
  init_output_scaling_actor:      [1.]                  # if list, then each qubit gets one param, if single float, all have same param [[1.], 1., ...]
  postprocessing_actor:           constant              # select postprocessing (check the file postprocessing.py)
  output_scaling_schedule:        False
  use_temperature:                False
  temperature_schedule:           [[0, 100_000], [1.00, 0.05]]   # number of increment steps, total steps
  ###########################################################################
  noise:                                                # use noise during training
    coherent:                     [False, 0.]           # bool + float for magnitude of used coherent noise
    depolarizing:                 [False, 0.001]        # bool + float for magnitude of used depolarizing noise
  layerwise_training:             False                 # layerwise training (DEPRECATED)
  gradient_clipping:              False                 # gradient clipping (DEPRECATED)
  use_classical_layer:            False                 # additional postprocessing (DEPRECATED)
  layer_size:                     [64, 64]              # classical NN, max 3 layers with in as number of neurons in the according layer
  activation_function:            relu                  # activation function of classical NN
  weight_logging_interval:        5000                  # weight logging + plotting interval (DEPRECATED)
  weight_plotting:                False                 # weight logging + plotting (DEPRECATED)
  ###########################################################################
  # More ray params
  explore:                        True


############################## Eval Config #############################################
evaluation:
  set_seed:               True 
  seed:                   42
  ###########################################################################
  plotting:
    mode:                         auto 
    y_axis:                       episode_reward_mean 
    path:                         logs/uc/paper_2/10units/2024-04-08--17-00-08_QRL_QPG
  